from click import clear
t1 = str(input('Digite a primera tarefa: '))
t2 = str(input('Digite a segunda tarefa: '))
t3 = str(input('Digite a terceira tarefa: '))
t4 = str(input('Digite a quarta tarefa: '))
t5 = str(input('Digite a quinta tarefa:'))
t6 = str(input('Digite a sexta tarefa: '))
t7 = str(input('Digite a setima tarefa: '))
t8 = str(input('Digite a oitava tarefa: '))
t9 = str(input('Digite a nona tarefa: '))
t10 = str(input('Digite a decima tarefa: '))

clear()

print('suas tarefas são: ')
print(f'1° = {t1}')
print(f'2° = {t2}')
print(f'3° = {t3}')
print(f'4° = {t4}')
print(f'5° = {t5}')
print(f'6° = {t6}')
print(f'7° = {t7}')
print(f'8° = {t8}')
print(f'9° = {t9}')
print(f'10° = {t10}')